### ISSUE TITLE
hanging while scanning a dir with 200_000 images

### ISSUE THREAD

**Issue by fvisconti** [dyne/harvest#10]
Hi guys!

I tried and scan a dir with 200k image file with the command: 

```
harvest -p DIR_PATH -t image --file
```

I get the prompt

```
Harvest DIR_PATH
type: image
```

and then it hangs indefinitely.

For comparison, `ls DIR_PATH` takes 0m1,543s to execute (and prompt all 200k files).

Am I doing something wrong?

**Comment by jaromil** [comment]
the lua implementation had issues and is commissioned now.

main executable is now the zsh shell script

I consider this a prototype for the final C implementation
