### ISSUE TITLE
mv and cp are not implemented so I wrote a wrapper

### ISSUE THREAD

**Issue by g-gundam** [dyne/harvest#5]
https://github.com/dyne/harvest/blob/a9466f9f995423ccc1073baa590c103db0ee93b1/src/harvest.lua#L168-L178

I like the idea behind harvest, and it was pretty close to what I needed for my ~/Downloads cleanup project, but I saw that the `mv` and `cp` commands were not implemented yet.  However, it seemed like I could make a wrapper around the current unfinished harvest and implement `cp` and `mv` myself.  The result was **[hvst](https://git.coom.tech/gg1234/hvst)**.

```
Usage:
  hvst
  hvst help
  hvst cp <TYPE> <DEST> [OPTION]...
  hvst mv <TYPE> <DEST> [OPTION]...

Examples:

  # Display help message.
  hvst help

  # List files in current directory.
  hvst

  # Copy all images to ~/Pictures.
  hvst cp image ~/Pictures

  # Copy all images to ~/Pictures and be verbose.
  hvst cp image ~/Pictures --verbose

  # Show what would happen if we tried to move all images to ~/Pictures/YYYY/MM.
  hvst mv image '@"~/Pictures/$_->{year}/$_->{month}"' --recon

  # Move all images to ~/Pictures/YYYY/MM.
  hvst mv image '@"~/Pictures/$_->{year}/$_->{month}"'

  # Both cp and mv commands take --verbose and --recon (or -v and -r for short).
```

I'm posting here in case someone finds this useful.

**Comment by jaromil** [comment]
@g-gundam thanks. the cp and mv are implemented in the older zsh version, but the new rewrite in lua needs polishing ( "works for me" basically ). will have a look at your code, would be nice to join hobby forces 😅

**Comment by g-gundam** [comment]
@jaromil I'm in a works-for-me situation myself since my wrapper implements the functionality I needed.  I feel like I captured the spirit of what harvest was trying to accomplish, but it is admittedly a quick and dirty hack done in a different language.  If the desire to learn Lua becomes strong enough, I may fill in some of the blanks in the Lua implementation.  However, for now, I'm going to thank you for doing the file scanning and categorization work that I was able to build upon.  It let me clean up my `~/Downloads` and `~/Pictures` directory which was a mess, and it will help me keep it clean going forward.

**Comment by jaromil** [comment]
No need to rewrite in another language I think is fine like that as long as it is reliable for the delicate task.

I read the code and seems very concise, which is a great plus.

Hope you don't mind if I include it inside harvest?

would you like to commit it yourself as a PR here? inside subdir `hvst` is OK
